// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

#include "Block.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace voxblox {
PROTOBUF_CONSTEXPR BlockProto::BlockProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.voxel_data_)*/ {}

  , /*decltype(_impl_.voxel_size_)*/ 0

  , /*decltype(_impl_.origin_x_)*/ 0

  , /*decltype(_impl_.voxels_per_side_)*/ 0

  , /*decltype(_impl_.has_data_)*/ false

  , /*decltype(_impl_.origin_y_)*/ 0

  , /*decltype(_impl_.origin_z_)*/ 0
} {}
struct BlockProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BlockProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BlockProtoDefaultTypeInternal() {}
  union {
    BlockProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BlockProtoDefaultTypeInternal _BlockProto_default_instance_;
}  // namespace voxblox
static ::_pb::Metadata file_level_metadata_Block_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Block_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Block_2eproto = nullptr;
const ::uint32_t TableStruct_Block_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::voxblox::BlockProto, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::voxblox::BlockProto, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::voxblox::BlockProto, _impl_.voxels_per_side_),
    PROTOBUF_FIELD_OFFSET(::voxblox::BlockProto, _impl_.voxel_size_),
    PROTOBUF_FIELD_OFFSET(::voxblox::BlockProto, _impl_.origin_x_),
    PROTOBUF_FIELD_OFFSET(::voxblox::BlockProto, _impl_.origin_y_),
    PROTOBUF_FIELD_OFFSET(::voxblox::BlockProto, _impl_.origin_z_),
    PROTOBUF_FIELD_OFFSET(::voxblox::BlockProto, _impl_.has_data_),
    PROTOBUF_FIELD_OFFSET(::voxblox::BlockProto, _impl_.voxel_data_),
    2,
    0,
    1,
    4,
    5,
    3,
    ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 15, -1, sizeof(::voxblox::BlockProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::voxblox::_BlockProto_default_instance_._instance,
};
const char descriptor_table_protodef_Block_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\013Block.proto\022\007voxblox\"\225\001\n\nBlockProto\022\027\n"
    "\017voxels_per_side\030\001 \001(\005\022\022\n\nvoxel_size\030\002 \001"
    "(\001\022\020\n\010origin_x\030\003 \001(\001\022\020\n\010origin_y\030\004 \001(\001\022\020"
    "\n\010origin_z\030\005 \001(\001\022\020\n\010has_data\030\006 \001(\010\022\022\n\nvo"
    "xel_data\030\007 \003(\r"
};
static ::absl::once_flag descriptor_table_Block_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Block_2eproto = {
    false,
    false,
    174,
    descriptor_table_protodef_Block_2eproto,
    "Block.proto",
    &descriptor_table_Block_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_Block_2eproto::offsets,
    file_level_metadata_Block_2eproto,
    file_level_enum_descriptors_Block_2eproto,
    file_level_service_descriptors_Block_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Block_2eproto_getter() {
  return &descriptor_table_Block_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Block_2eproto(&descriptor_table_Block_2eproto);
namespace voxblox {
// ===================================================================

class BlockProto::_Internal {
 public:
  using HasBits = decltype(std::declval<BlockProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(BlockProto, _impl_._has_bits_);
  static void set_has_voxels_per_side(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_voxel_size(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_origin_x(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_origin_y(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_origin_z(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_has_data(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

BlockProto::BlockProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:voxblox.BlockProto)
}
BlockProto::BlockProto(const BlockProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BlockProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.voxel_data_) { from._impl_.voxel_data_ }

    , decltype(_impl_.voxel_size_) {}

    , decltype(_impl_.origin_x_) {}

    , decltype(_impl_.voxels_per_side_) {}

    , decltype(_impl_.has_data_) {}

    , decltype(_impl_.origin_y_) {}

    , decltype(_impl_.origin_z_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.voxel_size_, &from._impl_.voxel_size_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.origin_z_) -
    reinterpret_cast<char*>(&_impl_.voxel_size_)) + sizeof(_impl_.origin_z_));
  // @@protoc_insertion_point(copy_constructor:voxblox.BlockProto)
}

inline void BlockProto::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.voxel_data_) { arena }

    , decltype(_impl_.voxel_size_) { 0 }

    , decltype(_impl_.origin_x_) { 0 }

    , decltype(_impl_.voxels_per_side_) { 0 }

    , decltype(_impl_.has_data_) { false }

    , decltype(_impl_.origin_y_) { 0 }

    , decltype(_impl_.origin_z_) { 0 }

  };
}

BlockProto::~BlockProto() {
  // @@protoc_insertion_point(destructor:voxblox.BlockProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BlockProto::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.voxel_data_.~RepeatedField();
}

void BlockProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BlockProto::Clear() {
// @@protoc_insertion_point(message_clear_start:voxblox.BlockProto)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.voxel_data_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    ::memset(&_impl_.voxel_size_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.origin_z_) -
        reinterpret_cast<char*>(&_impl_.voxel_size_)) + sizeof(_impl_.origin_z_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BlockProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 voxels_per_side = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_voxels_per_side(&has_bits);
          _impl_.voxels_per_side_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double voxel_size = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 17)) {
          _Internal::set_has_voxel_size(&has_bits);
          _impl_.voxel_size_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double origin_x = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 25)) {
          _Internal::set_has_origin_x(&has_bits);
          _impl_.origin_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double origin_y = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 33)) {
          _Internal::set_has_origin_y(&has_bits);
          _impl_.origin_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double origin_z = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 41)) {
          _Internal::set_has_origin_z(&has_bits);
          _impl_.origin_z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional bool has_data = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 48)) {
          _Internal::set_has_has_data(&has_bits);
          _impl_.has_data_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated uint32 voxel_data = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 56)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_voxel_data(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<56>(ptr));
        } else if (static_cast<::uint8_t>(tag) == 58) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_voxel_data(), ptr, ctx);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* BlockProto::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:voxblox.BlockProto)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 voxels_per_side = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        1, this->_internal_voxels_per_side(), target);
  }

  // optional double voxel_size = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this->_internal_voxel_size(), target);
  }

  // optional double origin_x = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this->_internal_origin_x(), target);
  }

  // optional double origin_y = 4;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        4, this->_internal_origin_y(), target);
  }

  // optional double origin_z = 5;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        5, this->_internal_origin_z(), target);
  }

  // optional bool has_data = 6;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        6, this->_internal_has_data(), target);
  }

  // repeated uint32 voxel_data = 7;
  for (int i = 0, n = this->_internal_voxel_data_size(); i < n; ++i) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        7, this->_internal_voxel_data(i), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:voxblox.BlockProto)
  return target;
}

::size_t BlockProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:voxblox.BlockProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 voxel_data = 7;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::UInt32Size(this->_impl_.voxel_data_)
    ;
    std::size_t tag_size = std::size_t{1} *
        ::_pbi::FromIntSize(this->_internal_voxel_data_size());
    ;
    total_size += tag_size + data_size;
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional double voxel_size = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 9;
    }

    // optional double origin_x = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 9;
    }

    // optional int32 voxels_per_side = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_voxels_per_side());
    }

    // optional bool has_data = 6;
    if (cached_has_bits & 0x00000008u) {
      total_size += 2;
    }

    // optional double origin_y = 4;
    if (cached_has_bits & 0x00000010u) {
      total_size += 9;
    }

    // optional double origin_z = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += 9;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BlockProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BlockProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BlockProto::GetClassData() const { return &_class_data_; }


void BlockProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BlockProto*>(&to_msg);
  auto& from = static_cast<const BlockProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:voxblox.BlockProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.voxel_data_.MergeFrom(from._impl_.voxel_data_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.voxel_size_ = from._impl_.voxel_size_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.origin_x_ = from._impl_.origin_x_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.voxels_per_side_ = from._impl_.voxels_per_side_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.has_data_ = from._impl_.has_data_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.origin_y_ = from._impl_.origin_y_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.origin_z_ = from._impl_.origin_z_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BlockProto::CopyFrom(const BlockProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:voxblox.BlockProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BlockProto::IsInitialized() const {
  return true;
}

void BlockProto::InternalSwap(BlockProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.voxel_data_.InternalSwap(&other->_impl_.voxel_data_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BlockProto, _impl_.origin_z_)
      + sizeof(BlockProto::_impl_.origin_z_)
      - PROTOBUF_FIELD_OFFSET(BlockProto, _impl_.voxel_size_)>(
          reinterpret_cast<char*>(&_impl_.voxel_size_),
          reinterpret_cast<char*>(&other->_impl_.voxel_size_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BlockProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Block_2eproto_getter, &descriptor_table_Block_2eproto_once,
      file_level_metadata_Block_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace voxblox
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::voxblox::BlockProto*
Arena::CreateMaybeMessage< ::voxblox::BlockProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::voxblox::BlockProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
