// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Layer.proto

#include "Layer.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace voxblox {
PROTOBUF_CONSTEXPR LayerProto::LayerProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.type_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.voxel_size_)*/ 0

  , /*decltype(_impl_.voxels_per_side_)*/ 0u
} {}
struct LayerProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LayerProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LayerProtoDefaultTypeInternal() {}
  union {
    LayerProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LayerProtoDefaultTypeInternal _LayerProto_default_instance_;
}  // namespace voxblox
static ::_pb::Metadata file_level_metadata_Layer_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Layer_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Layer_2eproto = nullptr;
const ::uint32_t TableStruct_Layer_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::voxblox::LayerProto, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::voxblox::LayerProto, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::voxblox::LayerProto, _impl_.voxel_size_),
    PROTOBUF_FIELD_OFFSET(::voxblox::LayerProto, _impl_.voxels_per_side_),
    PROTOBUF_FIELD_OFFSET(::voxblox::LayerProto, _impl_.type_),
    1,
    2,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 11, -1, sizeof(::voxblox::LayerProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::voxblox::_LayerProto_default_instance_._instance,
};
const char descriptor_table_protodef_Layer_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\013Layer.proto\022\007voxblox\"G\n\nLayerProto\022\022\n\n"
    "voxel_size\030\001 \001(\001\022\027\n\017voxels_per_side\030\002 \001("
    "\r\022\014\n\004type\030\003 \001(\t"
};
static ::absl::once_flag descriptor_table_Layer_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Layer_2eproto = {
    false,
    false,
    95,
    descriptor_table_protodef_Layer_2eproto,
    "Layer.proto",
    &descriptor_table_Layer_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_Layer_2eproto::offsets,
    file_level_metadata_Layer_2eproto,
    file_level_enum_descriptors_Layer_2eproto,
    file_level_service_descriptors_Layer_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Layer_2eproto_getter() {
  return &descriptor_table_Layer_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Layer_2eproto(&descriptor_table_Layer_2eproto);
namespace voxblox {
// ===================================================================

class LayerProto::_Internal {
 public:
  using HasBits = decltype(std::declval<LayerProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(LayerProto, _impl_._has_bits_);
  static void set_has_voxel_size(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_voxels_per_side(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

LayerProto::LayerProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:voxblox.LayerProto)
}
LayerProto::LayerProto(const LayerProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LayerProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.type_) {}

    , decltype(_impl_.voxel_size_) {}

    , decltype(_impl_.voxels_per_side_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.type_.Set(from._internal_type(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.voxel_size_, &from._impl_.voxel_size_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.voxels_per_side_) -
    reinterpret_cast<char*>(&_impl_.voxel_size_)) + sizeof(_impl_.voxels_per_side_));
  // @@protoc_insertion_point(copy_constructor:voxblox.LayerProto)
}

inline void LayerProto::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.type_) {}

    , decltype(_impl_.voxel_size_) { 0 }

    , decltype(_impl_.voxels_per_side_) { 0u }

  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LayerProto::~LayerProto() {
  // @@protoc_insertion_point(destructor:voxblox.LayerProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LayerProto::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.type_.Destroy();
}

void LayerProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LayerProto::Clear() {
// @@protoc_insertion_point(message_clear_start:voxblox.LayerProto)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.type_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.voxel_size_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.voxels_per_side_) -
        reinterpret_cast<char*>(&_impl_.voxel_size_)) + sizeof(_impl_.voxels_per_side_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LayerProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional double voxel_size = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 9)) {
          _Internal::set_has_voxel_size(&has_bits);
          _impl_.voxel_size_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 voxels_per_side = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _Internal::set_has_voxels_per_side(&has_bits);
          _impl_.voxels_per_side_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "voxblox.LayerProto.type");
          #endif  // !NDEBUG
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* LayerProto::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:voxblox.LayerProto)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional double voxel_size = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        1, this->_internal_voxel_size(), target);
  }

  // optional uint32 voxels_per_side = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_voxels_per_side(), target);
  }

  // optional string type = 3;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_type();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
                                "voxblox.LayerProto.type");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:voxblox.LayerProto)
  return target;
}

::size_t LayerProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:voxblox.LayerProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string type = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_type());
    }

    // optional double voxel_size = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += 9;
    }

    // optional uint32 voxels_per_side = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_voxels_per_side());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LayerProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LayerProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LayerProto::GetClassData() const { return &_class_data_; }


void LayerProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LayerProto*>(&to_msg);
  auto& from = static_cast<const LayerProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:voxblox.LayerProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_type(from._internal_type());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.voxel_size_ = from._impl_.voxel_size_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.voxels_per_side_ = from._impl_.voxels_per_side_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LayerProto::CopyFrom(const LayerProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:voxblox.LayerProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LayerProto::IsInitialized() const {
  return true;
}

void LayerProto::InternalSwap(LayerProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, lhs_arena,
                                       &other->_impl_.type_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LayerProto, _impl_.voxels_per_side_)
      + sizeof(LayerProto::_impl_.voxels_per_side_)
      - PROTOBUF_FIELD_OFFSET(LayerProto, _impl_.voxel_size_)>(
          reinterpret_cast<char*>(&_impl_.voxel_size_),
          reinterpret_cast<char*>(&other->_impl_.voxel_size_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LayerProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Layer_2eproto_getter, &descriptor_table_Layer_2eproto_once,
      file_level_metadata_Layer_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace voxblox
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::voxblox::LayerProto*
Arena::CreateMaybeMessage< ::voxblox::LayerProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::voxblox::LayerProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
